export const INJECTION_TOKENS = {
  // Repositories
  UserRepository: 'IUserRepository',
  PilotRepository: 'IPilotRepository',
  DroneRepository: 'IDroneRepository',
  CertificateRepository: 'ICertificateRepository',
  InsuranceRepository: 'IInsuranceRepository',
  MissionRepository: 'IMissionRepository',
  FlightLogRepository: 'IFlightLogRepository',
  TelemetryRepository: 'ITelemetryRepository',
  ChecklistRepository: 'IChecklistRepository',
  EmergencyContactRepository: 'IEmergencyContactRepository',
  EmergencyEventRepository: 'IEmergencyEventRepository',
  RefreshTokenRepository: 'IRefreshTokenRepository',
  // External providers
  WeatherProvider: 'IWeatherProvider',
  GeofenceProvider: 'IGeofenceProvider',
  DjiIntegrationProvider: 'IDjiIntegrationProvider',
  TokenProvider: 'ITokenProvider',
  PasswordHasher: 'IPasswordHasher',
  // Services
  AuthService: 'IAuthService',
  UserService: 'IUserService',
  PilotService: 'IPilotService',
  DroneService: 'IDroneService',
  CertificateService: 'ICertificateService',
  InsuranceService: 'IInsuranceService',
  MissionService: 'IMissionService',
  FlightLogService: 'IFlightLogService',
  TelemetryService: 'ITelemetryService',
  ChecklistService: 'IChecklistService',
  EmergencyService: 'IEmergencyService',
  WeatherService: 'IWeatherService',
  GeofenceService: 'IGeofenceService',
} as const;
